// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

import (
	"github.com/DataDog/datadog-agent/pkg/ebpf"
)

var RuntimeSecurity = ebpf.NewRuntimeAsset("runtime-security.c", "52edc3638b9cece6bea14a10d388963fe349a0de0fa29ee02481dd6d6fb08959")
