// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

import (
	"github.com/DataDog/datadog-agent/pkg/ebpf"
)

var Tracer = ebpf.NewRuntimeAsset("tracer.c", "b15f9a05420bba010d701e6c6bdb0c32d2f86b66335ef1606f5e52978ca88b0d")
