// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

import (
	"github.com/DataDog/datadog-agent/pkg/ebpf"
)

var Tracer = ebpf.NewRuntimeAsset("tracer.c", "8aa9f0b66f4979b21bb8e01cc563f3edc96e34acec9f580dd4d9042f7a11330b")
