// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

import (
	"github.com/DataDog/datadog-agent/pkg/ebpf"
)

var Tracer = ebpf.NewRuntimeAsset("tracer.c", "eb928c10fc68233bc8138362deb73c6048a77611f3b56d6cccec3ca6dcbff9b9")
